# Generated by Django 4.0.5 on 2022-07-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_historicalgoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='image',
            field=models.ImageField(default='media/images/not_found.png', upload_to='images', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalgoods',
            name='image',
            field=models.TextField(default='media/images/not_found.png', max_length=100, verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
